---
version: 2
ratings:
  paths:
  - "**.inc"
  - "**.ts"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
plugins:
  tslint:
    enabled: true
    config: tslint.json
