# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install packages
              run: yarn install

            - name: Build project
              run: yarn build

            - name: Run TSLint
              run: yarn lint

            - name: Run tests
              run: yarn test

    nix:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v31
            - run: nix flake check --print-build-logs
